

trigger:
- main

pool: santoshagentpool


steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'santoshpipelineservice'
    backendAzureRmStorageAccountName: 'santoshstorage2'
    backendAzureRmContainerName: 'santoshcontainer'
    backendAzureRmKey: 'santoshstatefile.terraform.tfstate'
- task: TerraformTask@5
  inputs:
    provider: 'azurerm'
    command: 'custom'
    commandOptions: 'fmt'
    outputTo: 'console'
    customCommand: 'fmt'
    environmentServiceNameAzureRM: 'santoshpipelineservice'